twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['helpers/frontend_form_layout.html.twig']
#    Creation of custom services for twig
    globals:
        breadcrumbs: '@App\Service\Breadcrumbs'
        menuGenerator: '@App\Service\MenuGenerator'